// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parking.FindingSlotManagement.Infrastructure.Persistences;

#nullable disable

namespace Parking.FindingSlotManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ParkZDbContext))]
    partial class ParkZDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("ParkingSlotId")
                        .HasColumnType("int")
                        .HasColumnName("ParkingSlotID");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("DateBook")
                        .HasColumnType("date");

                    b.Property<decimal?>("ActualPrice")
                        .HasColumnType("money");

                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"), 1L, 1);

                    b.Property<TimeSpan?>("CheckinTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("CheckoutTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("GuestName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GuestPhone")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(225)
                        .IsUnicode(false)
                        .HasColumnType("varchar(225)");

                    b.Property<string>("QrcodeText")
                        .HasMaxLength(225)
                        .IsUnicode(false)
                        .HasColumnType("varchar(225)")
                        .HasColumnName("QRCodeText");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TmnCodeVnPay")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("money");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int?>("VehicleInforId")
                        .HasColumnType("int")
                        .HasColumnName("VehicleInforID");

                    b.HasKey("ParkingSlotId", "StartTime", "DateBook")
                        .HasName("PK__Booking__1BDD09E6ABAB9F2E");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleInforId");

                    b.HasIndex(new[] { "BookingId" }, "UQ__Booking__3214EC2628BBAE14")
                        .IsUnique();

                    b.ToTable("Booking", (string)null);
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.BusinessProfile", b =>
                {
                    b.Property<int>("BusinessProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BusinessProfileId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessProfileId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BackIdentification")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BusinessLicense")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FrontIdentification")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("BusinessProfileId");

                    b.HasIndex(new[] { "UserId" }, "UQ__Business__1788CCAD877AB68C")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL");

                    b.ToTable("BusinessProfiles");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.FavoriteAddress", b =>
                {
                    b.Property<int>("FavoriteAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FavoriteAddressId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteAddressId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TagName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("FavoriteAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriteAddress", (string)null);
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.Floor", b =>
                {
                    b.Property<int>("FloorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FloorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FloorId"), 1L, 1);

                    b.Property<string>("FloorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ParkingId")
                        .HasColumnType("int")
                        .HasColumnName("ParkingID");

                    b.HasKey("FloorId");

                    b.HasIndex("ParkingId");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"), 1L, 1);

                    b.Property<string>("Body")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<TimeSpan?>("SentTime")
                        .HasColumnType("time");

                    b.Property<string>("Tiltle")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.HasKey("NotificationId");

                    b.HasIndex("BookingId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.PackagePrice", b =>
                {
                    b.Property<int>("PackagePriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PackagePriceId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackagePriceId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("ExtraFee")
                        .HasColumnType("money");

                    b.Property<float?>("ExtraTimeStep")
                        .HasColumnType("real");

                    b.Property<bool?>("HasPenaltyPrice")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsExtrafee")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("PenaltyPrice")
                        .HasColumnType("money");

                    b.Property<float?>("PenaltyPriceStepTime")
                        .HasColumnType("real");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("TrafficId")
                        .HasColumnType("int")
                        .HasColumnName("TrafficID");

                    b.HasKey("PackagePriceId");

                    b.HasIndex("TrafficId");

                    b.ToTable("PackagePrice", (string)null);
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.Parking", b =>
                {
                    b.Property<int>("ParkingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ParkingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParkingId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CarSpot")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFull")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOvernight")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPrepayment")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10,6)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("ManagerID");

                    b.Property<int?>("MotoSpot")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Stars")
                        .HasColumnType("int");

                    b.Property<int?>("StarsCount")
                        .HasColumnType("int");

                    b.HasKey("ParkingId");

                    b.ToTable("Parking", (string)null);
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.ParkingHasPrice", b =>
                {
                    b.Property<int>("ParkingHasPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ParkingHasPriceId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParkingHasPriceId"), 1L, 1);

                    b.Property<int?>("ParkingId")
                        .HasColumnType("int")
                        .HasColumnName("ParkingID");

                    b.Property<int?>("ParkingPriceId")
                        .HasColumnType("int")
                        .HasColumnName("ParkingPriceID");

                    b.HasKey("ParkingHasPriceId");

                    b.HasIndex("ParkingId");

                    b.HasIndex("ParkingPriceId");

                    b.ToTable("ParkingHasPrice", (string)null);
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.ParkingSlot", b =>
                {
                    b.Property<int>("ParkingSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ParkingSlotId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParkingSlotId"), 1L, 1);

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<int?>("ColumnIndex")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("FloorId")
                        .HasColumnType("int")
                        .HasColumnName("FloorID");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<int?>("ParkingId")
                        .HasColumnType("int")
                        .HasColumnName("ParkingID");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.Property<int?>("RowIndex")
                        .HasColumnType("int");

                    b.Property<int?>("TrafficId")
                        .HasColumnType("int")
                        .HasColumnName("TrafficID");

                    b.HasKey("ParkingSlotId");

                    b.HasIndex("BookingId");

                    b.HasIndex("FloorId");

                    b.HasIndex("ParkingId");

                    b.HasIndex("TrafficId");

                    b.ToTable("ParkingSlots");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.ParkingSpotImage", b =>
                {
                    b.Property<int>("ParkingSpotImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ParkingSpotImageId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParkingSpotImageId"), 1L, 1);

                    b.Property<string>("ImgPath")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ParkingId")
                        .HasColumnType("int")
                        .HasColumnName("ParkingID");

                    b.HasKey("ParkingSpotImageId");

                    b.HasIndex("ParkingId");

                    b.ToTable("ParkingSpotImage", (string)null);
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.PayPal", b =>
                {
                    b.Property<int>("PayPalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PayPalId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayPalId"), 1L, 1);

                    b.Property<string>("ClientId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("ManagerID");

                    b.Property<string>("SecretKey")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("PayPalId");

                    b.HasIndex("ManagerId");

                    b.ToTable("PayPal", (string)null);
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.StaffParking", b =>
                {
                    b.Property<int>("StaffParkingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StaffParkingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffParkingId"), 1L, 1);

                    b.Property<int?>("ParkingId")
                        .HasColumnType("int")
                        .HasColumnName("ParkingID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("StaffParkingId");

                    b.HasIndex("ParkingId");

                    b.HasIndex("UserId");

                    b.ToTable("StaffParking", (string)null);
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.Traffic", b =>
                {
                    b.Property<int>("TrafficId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TrafficId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrafficId"), 1L, 1);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TrafficId");

                    b.ToTable("Traffic", (string)null);
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Devicetoken")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCensorship")
                        .HasColumnType("bit");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("ManagerID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("UserId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.VehicleInfor", b =>
                {
                    b.Property<int>("VehicleInforId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VehicleInforId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleInforId"), 1L, 1);

                    b.Property<string>("Color")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<int?>("TrafficId")
                        .HasColumnType("int")
                        .HasColumnName("TrafficID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<string>("VehicleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VehicleInforId");

                    b.HasIndex("TrafficId");

                    b.HasIndex("UserId");

                    b.ToTable("VehicleInfor", (string)null);
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.VnPay", b =>
                {
                    b.Property<int>("VnPayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VnPayId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VnPayId"), 1L, 1);

                    b.Property<string>("HashSecret")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("ManagerID");

                    b.Property<string>("TmnCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("VnPayId");

                    b.HasIndex("ManagerId");

                    b.ToTable("VnPay", (string)null);
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.Booking", b =>
                {
                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Booking__UserID__5070F446");

                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.VehicleInfor", "VehicleInfor")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleInforId")
                        .HasConstraintName("FK__Booking__Vehicle__4F7CD00D");

                    b.Navigation("User");

                    b.Navigation("VehicleInfor");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.BusinessProfile", b =>
                {
                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.User", "User")
                        .WithOne("BusinessProfile")
                        .HasForeignKey("Parking.FindingSlotManagement.Domain.Entities.BusinessProfile", "UserId")
                        .HasConstraintName("fk_IsManager");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.FavoriteAddress", b =>
                {
                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.User", "User")
                        .WithMany("FavoriteAddresses")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__FavoriteA__UserI__33D4B598");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.Floor", b =>
                {
                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.Parking", "Parking")
                        .WithMany("Floors")
                        .HasForeignKey("ParkingId")
                        .HasConstraintName("FK__Floors__ParkingI__47DBAE45");

                    b.Navigation("Parking");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.Booking", "Booking")
                        .WithMany("Notifications")
                        .HasForeignKey("BookingId")
                        .HasPrincipalKey("BookingId")
                        .HasConstraintName("FK__Notificat__Booki__59063A47");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.PackagePrice", b =>
                {
                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.Traffic", "Traffic")
                        .WithMany("PackagePrices")
                        .HasForeignKey("TrafficId")
                        .HasConstraintName("FK__PackagePr__Traff__412EB0B6");

                    b.Navigation("Traffic");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.ParkingHasPrice", b =>
                {
                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.Parking", "Parking")
                        .WithMany("ParkingHasPrices")
                        .HasForeignKey("ParkingId")
                        .HasConstraintName("FK__ParkingHa__Parki__440B1D61");

                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.PackagePrice", "ParkingPrice")
                        .WithMany("ParkingHasPrices")
                        .HasForeignKey("ParkingPriceId")
                        .HasConstraintName("FK__ParkingHa__Parki__44FF419A");

                    b.Navigation("Parking");

                    b.Navigation("ParkingPrice");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.ParkingSlot", b =>
                {
                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.Booking", "Booking")
                        .WithMany("ParkingSlots")
                        .HasForeignKey("BookingId")
                        .HasPrincipalKey("BookingId")
                        .HasConstraintName("FK__ParkingSl__Booki__5629CD9C");

                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.Floor", "Floor")
                        .WithMany("ParkingSlots")
                        .HasForeignKey("FloorId")
                        .HasConstraintName("FK__ParkingSl__Floor__5441852A");

                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.Parking", "Parking")
                        .WithMany("ParkingSlots")
                        .HasForeignKey("ParkingId")
                        .HasConstraintName("FK__ParkingSl__Parki__5535A963");

                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.Traffic", "Traffic")
                        .WithMany("ParkingSlots")
                        .HasForeignKey("TrafficId")
                        .HasConstraintName("FK__ParkingSl__Traff__534D60F1");

                    b.Navigation("Booking");

                    b.Navigation("Floor");

                    b.Navigation("Parking");

                    b.Navigation("Traffic");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.ParkingSpotImage", b =>
                {
                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.Parking", "Parking")
                        .WithMany("ParkingSpotImages")
                        .HasForeignKey("ParkingId")
                        .HasConstraintName("FK__ParkingSp__Parki__3C69FB99");

                    b.Navigation("Parking");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.PayPal", b =>
                {
                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.User", "Manager")
                        .WithMany("PayPals")
                        .HasForeignKey("ManagerId")
                        .HasConstraintName("FK__PayPal__ManagerI__2D27B809");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.StaffParking", b =>
                {
                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.Parking", "Parking")
                        .WithMany("StaffParkings")
                        .HasForeignKey("ParkingId")
                        .HasConstraintName("FK__StaffPark__Parki__398D8EEE");

                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.User", "User")
                        .WithMany("StaffParkings")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__StaffPark__UserI__38996AB5");

                    b.Navigation("Parking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.User", b =>
                {
                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.User", "Manager")
                        .WithMany("InverseManager")
                        .HasForeignKey("ManagerId")
                        .HasConstraintName("FK__Users__ManagerID__267ABA7A");

                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Users__RoleID__276EDEB3");

                    b.Navigation("Manager");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.VehicleInfor", b =>
                {
                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.Traffic", "Traffic")
                        .WithMany("VehicleInfors")
                        .HasForeignKey("TrafficId")
                        .HasConstraintName("FK__VehicleIn__Traff__4BAC3F29");

                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.User", "User")
                        .WithMany("VehicleInfors")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__VehicleIn__UserI__4AB81AF0");

                    b.Navigation("Traffic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.VnPay", b =>
                {
                    b.HasOne("Parking.FindingSlotManagement.Domain.Entities.User", "Manager")
                        .WithMany("VnPays")
                        .HasForeignKey("ManagerId")
                        .HasConstraintName("FK__VnPay__ManagerID__2A4B4B5E");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("ParkingSlots");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.Floor", b =>
                {
                    b.Navigation("ParkingSlots");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.PackagePrice", b =>
                {
                    b.Navigation("ParkingHasPrices");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.Parking", b =>
                {
                    b.Navigation("Floors");

                    b.Navigation("ParkingHasPrices");

                    b.Navigation("ParkingSlots");

                    b.Navigation("ParkingSpotImages");

                    b.Navigation("StaffParkings");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.Traffic", b =>
                {
                    b.Navigation("PackagePrices");

                    b.Navigation("ParkingSlots");

                    b.Navigation("VehicleInfors");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("BusinessProfile");

                    b.Navigation("FavoriteAddresses");

                    b.Navigation("InverseManager");

                    b.Navigation("PayPals");

                    b.Navigation("StaffParkings");

                    b.Navigation("VehicleInfors");

                    b.Navigation("VnPays");
                });

            modelBuilder.Entity("Parking.FindingSlotManagement.Domain.Entities.VehicleInfor", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
